use single Python Version for API container CI/CD and tox
repository-service-tuf/repository-service-tuf-api pull request #719
Opened 2024-10-18 11:49 UTC by Brijeshthummar02

# Description
use single Python Version for API container CI/CD and tox 

Fixes #717 

# Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality not to work as expected)

# Additional requirements
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

# Code of Conduct
By submitting this PR, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.rst).

- [x] I agree to follow this project's Code of Conduct

2024-10-18 11:51 UTC, Brijeshthummar02 commented
@kairoaraujo please go through the pr.

2024-10-18 12:35 UTC, kairoaraujo requested changes
Missing changes on[ tox.ini](https://github.com/repository-service-tuf/repository-service-tuf-api/blob/main/tox.ini)

2024-10-18 15:24 UTC, MVrachev reviewed
Could you also change those places to python3.12:
- https://github.com/repository-service-tuf/repository-service-tuf-api/blob/ba2190f647c86456b4f1b41236c383e6a3c604e7/docker-compose.yml#L73
- https://github.com/repository-service-tuf/repository-service-tuf-api/blob/ba2190f647c86456b4f1b41236c383e6a3c604e7/README.rst#development-tools - to `Python >=3.12`
- https://github.com/repository-service-tuf/repository-service-tuf-api/blob/ba2190f647c86456b4f1b41236c383e6a3c604e7/.github/workflows/publish_container.yml#L33
- https://github.com/repository-service-tuf/repository-service-tuf-api/blob/ba2190f647c86456b4f1b41236c383e6a3c604e7/.github/workflows/update-pre-commit-hooks.yml#L14
- https://github.com/repository-service-tuf/repository-service-tuf-api/blob/ba2190f647c86456b4f1b41236c383e6a3c604e7/.github/workflows/ci.yml#L15   @kairoaraujo I think we don't need to run it for  `3.10` and `3.11`, correct? We can only use `3.12`?

2024-10-18 15:33 UTC, Brijeshthummar02 commented
@MVrachev there you go, i have made changes as you mentioned.

2024-10-19 11:47 UTC, kairoaraujo approved these changes

2024-10-19 15:32 UTC, kairoaraujo approved these changes

2024-10-19 15:34 UTC, kairoaraujo requested changes

2024-10-19 15:34 UTC, kairoaraujo commented on docker-compose.yml
> +    image: python:3.12-slim-buster
```suggestion
    image: python:3.12-slim
```
There is no buster for 3.12 slim

2024-10-19 15:42 UTC, Brijeshthummar02 commented
@kairoaraujo resolved as mentioned by you.

2024-10-19 15:42 UTC, kairoaraujo approved these changes

2024-10-19 15:47 UTC, Brijeshthummar02 commented
@kairoaraujo is it good to go now?

2024-10-19 15:47 UTC, merged

2024-10-19 15:48 UTC, kairoaraujo commented
Thank you @Brijeshthummar02 
We hope you engage in the RSTUF project.

2024-10-19 15:49 UTC, Brijeshthummar02 commented
@kairoaraujo yeah, i would stick to the RSTFU projects.